<div align="center">
МІНІСТЕРСТВО ОСВІТИ І НАУКИ УКРАЇНИ<br>
ІНСТИТУТ ПРИКЛАДНОГО СИСТЕМНОГО АНАЛІЗУ<br>
НАЦІОНАЛЬНОГО ТЕХНІЧНОГО УНІВЕРСИТЕТУ УКРАЇНИ<br>
«КИЇВСЬКИЙ ПОЛІТЕХНІЧНИЙ ІНСТИТУТ»<br>
КАФЕДРА МАТЕМАТИЧНИХ МЕТОДІВ СИСТЕМНОГО АНАЛІЗУ<br>
</div>
<br><br><br><br><br><br><br><br>
<div align="center"><strong>Лабораторна робота №1</strong></div>
<div align="center">З курсу "Інтелектуальні системи підтримки прийняття рішень"</div>
<div align="center">Тема "Basic Python"</div>
<br><br><br><br>
<div align="right">
    <strong>Виконав:</strong><br>
    Студент группи КА-81<br>
    Єрко А.В.<br><br>
    <strong>Прийняла:</strong><br>
    Недашківська Н.І.
</div>
<br><br><br><br><br><br><br>
<center>Київ - 2021</center>


<hr>

**Варіант 3.** Дано масив $T$, який складається з $N$ рядків, які відповідають прикладам, і $m$ стовпчиків, які відповідають ознакам. Відомо, що ознака $x_h$ приймає значення з множини $\{c_{h_1}, c_{h_2} \dots c_{h_{q_h}}\}$.
Дано вектор $y$ розмірності $N$, елементи якого приймають значення з множини $S = \{s_1, s_2 \dots s_v\}$ (мітки классів для прикладів).

Знайти ознаку $x^*_h$, для якої наступний вираз приймає мінімальне значення:
$$
    G(x_h) = \sum^{q_h}_{i=1} \frac{|T_i|}{N} H(T_i, S). \qquad (1)
$$
Де $T_i$ - підмножина прикладів, для яких ознака $x_h$ приймає значення $c_{h_i}$, $|A|$ - потужність множини $A$, $H(A,S)$ - індекс Джині множини $A$ по відношенню до властивості S:
$$
    H(A,S) = 1 -\sum^{v}_{i=1} \left( \frac{k_i}{|A|} \right)^2, \qquad (2)
$$
де властивість $S$ може приймати $v$ різних значень, кожне з яких в $k_i$ випадках.

**Реалізація:**

In [1]:
import numpy as np

In [2]:
def gini_impurity(A): # Індекс Джині (2)
    return 1 - ( (np.unique(A, return_counts=True)[1] / A.shape[0])**2 ).sum()

In [3]:
def g_expression(x, y):  # вираз (1)
    c_h, n_h = np.unique(x, return_counts=True)
    return (n_h/x.size * [gini_impurity(y[x == c]) for c in c_h]).sum()

In [4]:
def find_best_feature(T, y):
    '''
    T : np.ndarray of (N, m) - матриця прикладів
    y : np.ndarray of (N, ) - вектор ознак
    
    Повертає номер ознаки (стовбця масиву T)
    для якої значення виразу (1) відносно y - мінімальне
    та вектор значень виразу для кожноъ ознаки.
    '''
    G = np.apply_along_axis(g_expression, axis=0, arr=T, y=y)
    return G.argmin(), G

Згенеруємо приклад для перевірки реалізованих функцій:

In [5]:
N = 10  # number of observations
m = 5  # number of features
q_h = 4  # number of different values for each feature
v = 3 # number of different labels

np.random.seed(123)
T = np.random.randint(q_h ,size=(N,m))
y = np.random.randint(v, size=N)
display(T)
display(y)

array([[2, 1, 2, 2, 0],
       [2, 2, 1, 3, 2],
       [3, 1, 2, 1, 0],
       [1, 2, 3, 1, 0],
       [2, 0, 3, 1, 3],
       [2, 1, 0, 0, 0],
       [0, 1, 3, 3, 2],
       [0, 3, 2, 0, 3],
       [0, 1, 0, 3, 1],
       [3, 0, 0, 0, 2]])

array([1, 1, 2, 2, 2, 1, 0, 0, 2, 1])

In [6]:
rez = find_best_feature(T, y)
print(f"Значення виразу мінімальне для {rez[0]} ознаки")
print("Відповідні значення виразу для кожної ознаки:")
display(rez[1])

Значення виразу мінімальне для 3 ознаки
Відповідні значення виразу для кожної ознаки:


array([0.38333333, 0.52      , 0.46666667, 0.33333333, 0.43333333])